### ISSUE TITLE
Is arm support for Raspberry Pi & IoT in general coming?

### ISSUE THREAD

**Issue by wouterds** [docker-library/php#364]
Was experimenting with docker on my Raspberry Pi only to find out that I can't install any extensions.

```
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
        panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x336168, 0x56eb3c80)
        /usr/local/go/src/runtime/panic.go:481 +0x330
github.com/urfave/cli.HandleAction.func1(0x56f0d958)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x328
panic(0x336168, 0x56eb3c80)
        /usr/local/go/src/runtime/panic.go:443 +0x448
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x56f0d5e0, 0x56e38290, 0x56f0d668)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x13c
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x56eb42a0, 0x4648d490, 0x56eb3c80)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x498
main.glob.func8(0x56ec41e0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x58
reflect.Value.call(0x2eb6a0, 0x3f2a00, 0x13, 0x364970, 0x4, 0x56f0d918, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0xeb4
reflect.Value.Call(0x2eb6a0, 0x3f2a00, 0x13, 0x56f0d918, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0x84
github.com/urfave/cli.HandleAction(0x2eb6a0, 0x3f2a00, 0x56ec41e0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x230
github.com/urfave/cli.Command.Run(0x366d90, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3d0e08, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xcd0
github.com/urfave/cli.(*App).Run(0x56e9e240, 0x56e80050, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x84c
main.main()
        /go/src/github.com/opencontainers/runc/main.go:137 +0xbb4
```

![Screenshot](https://www.dropbox.com/s/x4kgb0y0r1wridu/screenshot-terminal-docker-php-rpi.jpg?dl=1)

**Comment by nsteinmetz** [comment]
I use the arm version of [hypriot](https://blog.hypriot.com/) and it works like a charm. Look at the downloads page to fetch latest version.

I could recompile official `php:7-fpm-alpine` by just replacing official `alpine:3.4` to `armhf/alpine:3.4` in the docker file.

**Comment by yosifkit** [comment]
There are many experimental builds of official images that are available for other architectures; there is an armhf version for php available in https://hub.docker.com/r/armhf/php/.  See the [official images' readme](https://github.com/docker-library/official-images/tree/ef9204dddf64b94a23dbeec229078a8f19dfdcd0#architectures-other-than-amd64) for more information.

**Comment by tianon** [comment]
This was officially fixed by https://github.com/docker-library/php/pull/454. :+1: :metal:
